export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM';
export const FETCH_ORDER = 'FETCH_ORDER';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const HIDE_MODAL = 'HIDE_MODAL';
export const REMOVE_ORDER_ITEM = 'REMOVE_ORDER_ITEM';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SHOW_MODAL = 'SHOW_MODAL';
